/**
 * Development Database Seed
 *
 * Seeds the development database with sample data for testing and development.
 * Uses the hybrid seed architecture with better-auth for users and
 * manual seeding for other tables.
 *
 * Usage:
 *   npm run db:seed
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { checkDatabaseConnection, closeDatabaseConnection } from "./db";
import { runDevSeed } from "./lib/seed";
import { logger } from "./lib/logger";

/**
 * Update .env file with MCP configuration
 */
function updateEnvWithMcpConfig(apiKey: string, organizationId: string): void {
  const envPath = join(import.meta.dirname, "..", ".env");

  if (!existsSync(envPath)) {
    logger.warn(".env file not found, skipping MCP config update");
    return;
  }

  let envContent = readFileSync(envPath, "utf-8");

  // Update or add INSIGHTDESK_API_KEY
  if (envContent.includes("INSIGHTDESK_API_KEY=")) {
    envContent = envContent.replace(/INSIGHTDESK_API_KEY=.*/g, `INSIGHTDESK_API_KEY=${apiKey}`);
  } else {
    envContent += `\n# MCP Configuration (auto-generated by db:seed)\nINSIGHTDESK_API_KEY=${apiKey}\n`;
  }

  // Update or add INSIGHTDESK_ORGANIZATION_ID
  if (envContent.includes("INSIGHTDESK_ORGANIZATION_ID=")) {
    envContent = envContent.replace(
      /INSIGHTDESK_ORGANIZATION_ID=.*/g,
      `INSIGHTDESK_ORGANIZATION_ID=${organizationId}`,
    );
  } else {
    envContent += `INSIGHTDESK_ORGANIZATION_ID=${organizationId}\n`;
  }

  writeFileSync(envPath, envContent);
  logger.info("Updated .env with MCP configuration");
}

/**
 * Generate Claude Desktop configuration JSON
 */
function generateClaudeDesktopConfig(apiKey: string, organizationId: string): string {
  const cwd = join(import.meta.dirname, "..").replace(/\\/g, "/");
  return JSON.stringify(
    {
      mcpServers: {
        insightdesk: {
          command: "bun",
          args: ["run", "mcp"],
          cwd,
          env: {
            INSIGHTDESK_API_KEY: apiKey,
            INSIGHTDESK_ORGANIZATION_ID: organizationId,
          },
        },
      },
    },
    null,
    2,
  );
}

async function seed() {
  logger.info("Starting development database seed...");

  // Check database connection
  const connected = await checkDatabaseConnection();
  if (!connected) {
    logger.error("Failed to connect to database");
    process.exit(1);
  }

  try {
    const result = await runDevSeed();

    logger.info("=".repeat(50));
    logger.info("Seed completed successfully!");
    logger.info("=".repeat(50));
    logger.info(`Users created: ${result.userIds.length}`);
    logger.info(`Organizations created: ${result.organizationIds.length}`);
    logger.info(`Categories created: ${result.categoryIds.length}`);
    logger.info(`Tags created: ${result.tagIds.length}`);
    logger.info(`Subscription plans created: ${result.planIds.length}`);
    logger.info(`Tickets created: ${result.ticketIds.length}`);
    logger.info("=".repeat(50));
    logger.info("");
    logger.info("You can now login with:");
    logger.info("  Email: owner@acme.com");
    logger.info("  Password: Owner123!");
    logger.info("");
    logger.info("Or with other users:");
    logger.info("  admin@acme.com / Admin123!");
    logger.info("  agent@acme.com / Agent123!");
    logger.info("  customer@acme.com / Customer123!");
    logger.info("=".repeat(50));

    // Update .env with MCP configuration
    updateEnvWithMcpConfig(result.mcpConfig.apiKey, result.mcpConfig.organizationId);

    // Output MCP configuration
    logger.info("");
    logger.info("╔══════════════════════════════════════════════════════════╗");
    logger.info("║           MCP Configuration                              ║");
    logger.info("╚══════════════════════════════════════════════════════════╝");
    logger.info("");
    logger.info("API Key and Organization ID have been added to .env");
    logger.info("You can now run: bun run mcp");
    logger.info("");
    logger.info("For Claude Desktop, add to your config:");
    logger.info("  macOS: ~/Library/Application Support/Claude/claude_desktop_config.json");
    logger.info("  Windows: %APPDATA%\\Claude\\claude_desktop_config.json");
    logger.info("");
    logger.info("Claude Desktop MCP config JSON:");
    logger.info(
      generateClaudeDesktopConfig(result.mcpConfig.apiKey, result.mcpConfig.organizationId),
    );
    logger.info("");
    logger.info("=".repeat(50));

    // Close connection and exit successfully
    await closeDatabaseConnection();
    process.exit(0);
  } catch (error) {
    logger.error({ err: error }, "Seed failed");
    await closeDatabaseConnection();
    process.exit(1);
  }
}

seed();
